/**
 * Ready-to-paste React + ECharts snippet emitter.
 *
 * Given the current chart kind, palette hexes, dash/decal/shape scales and
 * theme tokens, produce a self-contained `<ChartName>.tsx` file the user can
 * drop straight into a Vite / Next / CRA project. No imports from this
 * design tool — only `react`, `echarts`, and `echarts-for-react`.
 *
 * This is the "handoff" path for engineers who don't want to ship the whole
 * token system: paste a chart, get the colors the auditor already approved.
 */
import type { ChartTheme } from "./echartsTheme";
import { CHART_KIND_LABEL, type ChartKind } from "./chartKinds";

function safeComponentName(kind: ChartKind): string {
  return kind
    .split("-")
    .map((s) => s[0]?.toUpperCase() + s.slice(1))
    .join("") + "Chart";
}

function literal(arr: unknown[]): string {
  return JSON.stringify(arr);
}

export function buildCodeSnippet(args: {
  kind: ChartKind;
  n: number;
  theme: ChartTheme;
}): string {
  const { kind, n, theme } = args;
  const colors = theme.colorHexes.slice(0, n);
  const dashes = theme.dashes.slice(0, n);
  const decals = theme.decals.slice(0, n);
  const shapes = theme.shapes.slice(0, n);
  const t = theme.tokens;
  const componentName = safeComponentName(kind);
  const tokensJson = JSON.stringify(
    {
      bg: t.bg.hex,
      axis: t.axis.hex,
      grid: t.grid.hex,
      tooltipBg: t.tooltipBg.hex,
      tooltipFg: t.tooltipFg.hex,
    },
    null,
    2
  );

  // Per-kind option builder — we only template the common cases the user
  // sees in the demo. The rest fall back to a generic line example.
  let seriesBlock = "";
  let extras = "";
  switch (kind) {
    case "bar":
    case "stacked-bar":
    case "grouped-bar":
    case "horizontal-bar": {
      const stack = kind === "stacked-bar" ? `stack: "total",` : "";
      const swap = kind === "horizontal-bar";
      seriesBlock = `series: data.map((s, i) => ({
      name: s.name,
      type: "bar",
      ${stack}
      data: s.data,
      itemStyle: { color: PALETTE[i % PALETTE.length], decal: DECALS[i % DECALS.length] },
    })),`;
      extras = `aria: { enabled: true, decal: { show: true } },
    ${swap ? `xAxis: { type: "value" }, yAxis: { type: "category", data: categories },`
            : `xAxis: { type: "category", data: categories }, yAxis: { type: "value" },`}`;
      break;
    }
    case "pie":
    case "donut": {
      const radius = kind === "donut" ? `["45%", "75%"]` : `["0%", "70%"]`;
      seriesBlock = `series: [{
      type: "pie",
      radius: ${radius},
      data: data.map((d, i) => ({
        name: d.name,
        value: d.value,
        itemStyle: { color: PALETTE[i % PALETTE.length], decal: DECALS[i % DECALS.length] },
      })),
    }],`;
      extras = `aria: { enabled: true, decal: { show: true } },`;
      break;
    }
    case "scatter": {
      seriesBlock = `series: data.map((s, i) => ({
      name: s.name,
      type: "scatter",
      symbol: SHAPES[i % SHAPES.length],
      symbolSize: 12,
      itemStyle: { color: PALETTE[i % PALETTE.length] },
      data: s.points,
    })),`;
      extras = `xAxis: { type: "value" }, yAxis: { type: "value" },`;
      break;
    }
    default: {
      // line, step-line, area, stacked-area, etc.
      const area = kind === "area" || kind === "stacked-area";
      const stack = kind === "stacked-area" ? `stack: "total",` : "";
      const step = kind === "step-line" ? `step: "middle",` : "";
      seriesBlock = `series: data.map((s, i) => ({
      name: s.name,
      type: "line",
      ${step}
      ${stack}
      data: s.data,
      color: PALETTE[i % PALETTE.length],
      symbol: SHAPES[i % SHAPES.length],
      lineStyle: { width: 2, type: DASHES[i % DASHES.length] },
      itemStyle: { color: PALETTE[i % PALETTE.length] },
      ${area ? `areaStyle: { opacity: 0.4 },` : ""}
    })),`;
      extras = `xAxis: { type: "value" }, yAxis: { type: "value" },`;
    }
  }

  return `// ${CHART_KIND_LABEL[kind]} — generated by the chart palette tool.
// Palette is pre-audited for OKLab ΔE, CVD (deutan/protan/tritan), and WCAG
// contrast vs. background. Keep slot order to keep entity → color stable.
//
// npm i echarts echarts-for-react
import ReactECharts from "echarts-for-react";

const PALETTE = ${literal(colors)};
const DASHES  = ${literal(dashes.map((d) => (d === "solid" ? "solid" : d)))};
const DECALS  = ${literal(decals)};
const SHAPES  = ${literal(shapes)};
const TOKENS  = ${tokensJson};

export interface ${componentName}Props {
  data: Array<{ name: string; data?: number[]; points?: number[][]; value?: number }>;
  categories?: string[];
  height?: number | string;
}

export function ${componentName}({ data, categories = [], height = 360 }: ${componentName}Props) {
  const option = {
    backgroundColor: TOKENS.bg,
    textStyle: { color: TOKENS.axis },
    grid: { top: 32, left: 56, right: 24, bottom: 40, containLabel: true },
    tooltip: { backgroundColor: TOKENS.tooltipBg, textStyle: { color: TOKENS.tooltipFg } },
    legend: { textStyle: { color: TOKENS.axis }, top: 0 },
    ${extras}
    ${seriesBlock}
  };
  return <ReactECharts option={option} style={{ height, width: "100%" }} />;
}
`;
}
