/**
 * Palette export — turn the currently rendered chart theme into shippable
 * artifacts for design + engineering handoff.
 *
 * Every emitter is pure: input is a `PaletteExport` snapshot, output is a
 * string. The UI layer handles copy-to-clipboard and file download.
 *
 * Formats:
 *   - CSS variables   → drop into your design system's :root / .dark blocks
 *   - Tailwind config → extend.colors.chart.* references
 *   - ECharts theme   → registerTheme(name, JSON)
 *   - Figma Tokens    → W3C-style JSON consumed by Figma Tokens / Tokens Studio
 *   - SVG swatches    → 1-page palette sheet for slides/specs
 */
import type { ChartTheme, Theme } from "./echartsTheme";
import type { ColorRecord } from "./palette/distance";
import { sequentialRamp, divergingRamp } from "./palette/ramps";
import { PALETTE_VERSION } from "./version";

export interface PaletteExport {
  /** Friendly name used in filenames and theme IDs. */
  name: string;
  theme: Theme;
  /** Variant A theme — the only required theme. */
  themeA: ChartTheme;
  /** Optional Variant B (when compare is on with normal vision). */
  themeB?: ChartTheme;
  /** Number of ramp stops for sequential/diverging exports. */
  rampSteps?: number;
}

function safeName(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "palette";
}

/** XML-escape free text before interpolating it into SVG markup. The SVG
 *  export is previewed via dangerouslySetInnerHTML, so an unescaped name
 *  like `<img onerror=...>` would execute in the preview pane. */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function hex(c: ColorRecord): string {
  return c.hex.toUpperCase();
}

function categoricalSlots(theme: ChartTheme): string[] {
  return theme.solve.palette.map((c) => hex(c));
}

function sequentialStops(theme: ChartTheme, steps: number): string[] {
  return sequentialRamp(theme.tokens.seqLow, theme.tokens.seqHigh, steps).map((c) => hex(c));
}

function divergingStops(theme: ChartTheme, steps: number): string[] {
  return divergingRamp(theme.tokens.divNeg, theme.tokens.divMid, theme.tokens.divPos, steps).map(
    (c) => hex(c)
  );
}

/** CSS custom-properties block. Emits one selector per included theme. */
export function toCss(exp: PaletteExport): string {
  const steps = exp.rampSteps ?? 9;
  function block(label: string, t: ChartTheme): string {
    const cats = categoricalSlots(t);
    const seq = sequentialStops(t, steps);
    const div = divergingStops(t, steps);
    const lines: string[] = [];
    lines.push(`  /* ${label} — ${t.theme} theme · N=${t.effectiveN} · posture=${t.posture} */`);
    lines.push(`  --chart-bg: ${hex(t.tokens.bg)};`);
    lines.push(`  --chart-surface: ${hex(t.tokens.surface)};`);
    lines.push(`  --chart-grid: ${hex(t.tokens.grid)};`);
    lines.push(`  --chart-axis: ${hex(t.tokens.axis)};`);
    cats.forEach((c, i) => lines.push(`  --chart-cat-${i + 1}: ${c};`));
    seq.forEach((c, i) => lines.push(`  --chart-seq-${i + 1}: ${c};`));
    div.forEach((c, i) => lines.push(`  --chart-div-${i + 1}: ${c};`));
    lines.push(`  --chart-positive: ${hex(t.tokens.positive)};`);
    lines.push(`  --chart-negative: ${hex(t.tokens.negative)};`);
    return lines.join("\n");
  }
  const aSelector = exp.themeA.theme === "dark" ? ".dark" : ":root";
  const out: string[] = [];
  out.push(`/* Generated by ${exp.name} · palette v${PALETTE_VERSION} */`);
  out.push(`${aSelector} {`);
  out.push(block("Variant A", exp.themeA));
  out.push(`}`);
  if (exp.themeB) {
    const bSelector =
      exp.themeB.theme === "dark"
        ? `.dark[data-chart-variant="b"]`
        : `:root[data-chart-variant="b"]`;
    out.push(``);
    out.push(`${bSelector} {`);
    out.push(block("Variant B", exp.themeB));
    out.push(`}`);
  }
  return out.join("\n") + "\n";
}

/** Tailwind v3 config snippet referencing the CSS variables above. */
export function toTailwind(exp: PaletteExport): string {
  const steps = exp.rampSteps ?? 9;
  const cats = categoricalSlots(exp.themeA);
  const seq = sequentialStops(exp.themeA, steps);
  const div = divergingStops(exp.themeA, steps);
  const lines: string[] = [];
  lines.push(`// Generated by ${exp.name} · palette v${PALETTE_VERSION}`);
  lines.push(`// Paste under tailwind.config.ts → theme.extend.colors`);
  lines.push(`module.exports = {`);
  lines.push(`  chart: {`);
  lines.push(`    bg: "var(--chart-bg)",`);
  lines.push(`    surface: "var(--chart-surface)",`);
  lines.push(`    grid: "var(--chart-grid)",`);
  lines.push(`    axis: "var(--chart-axis)",`);
  lines.push(`    positive: "var(--chart-positive)",`);
  lines.push(`    negative: "var(--chart-negative)",`);
  lines.push(`    cat: {`);
  cats.forEach((_, i) => lines.push(`      ${i + 1}: "var(--chart-cat-${i + 1})",`));
  lines.push(`    },`);
  lines.push(`    seq: {`);
  seq.forEach((_, i) => lines.push(`      ${i + 1}: "var(--chart-seq-${i + 1})",`));
  lines.push(`    },`);
  lines.push(`    div: {`);
  div.forEach((_, i) => lines.push(`      ${i + 1}: "var(--chart-div-${i + 1})",`));
  lines.push(`    },`);
  lines.push(`  },`);
  lines.push(`};`);
  return lines.join("\n") + "\n";
}

/** ECharts `registerTheme` payload. */
export function toEChartsTheme(exp: PaletteExport): string {
  const t = exp.themeA;
  const steps = exp.rampSteps ?? 9;
  const payload = {
    name: safeName(exp.name),
    version: PALETTE_VERSION,
    color: categoricalSlots(t),
    backgroundColor: hex(t.tokens.bg),
    textStyle: { color: hex(t.tokens.axis) },
    title: { textStyle: { color: hex(t.tokens.axis) } },
    legend: { textStyle: { color: hex(t.tokens.axis) } },
    tooltip: {
      backgroundColor: hex(t.tokens.tooltipBg),
      textStyle: { color: hex(t.tokens.tooltipFg) },
      borderWidth: 0,
    },
    categoryAxis: {
      axisLine: { lineStyle: { color: hex(t.tokens.axis) } },
      axisLabel: { color: hex(t.tokens.axis) },
      splitLine: { lineStyle: { color: hex(t.tokens.grid) } },
    },
    valueAxis: {
      axisLine: { lineStyle: { color: hex(t.tokens.axis) } },
      axisLabel: { color: hex(t.tokens.axis) },
      splitLine: { lineStyle: { color: hex(t.tokens.grid) } },
    },
    visualMap: {
      sequential: { color: sequentialStops(t, steps) },
      diverging: { color: divergingStops(t, steps) },
    },
  };
  return JSON.stringify(payload, null, 2) + "\n";
}

/** Figma Tokens / Tokens Studio JSON (W3C-ish flat shape). */
export function toFigmaTokens(exp: PaletteExport): string {
  const t = exp.themeA;
  const steps = exp.rampSteps ?? 9;
  const cats = categoricalSlots(t);
  const seq = sequentialStops(t, steps);
  const div = divergingStops(t, steps);
  function token(value: string) {
    return { value, type: "color" };
  }
  const set: Record<string, unknown> = {
    chart: {
      surface: {
        bg: token(hex(t.tokens.bg)),
        surface: token(hex(t.tokens.surface)),
        grid: token(hex(t.tokens.grid)),
        axis: token(hex(t.tokens.axis)),
      },
      semantic: {
        positive: token(hex(t.tokens.positive)),
        negative: token(hex(t.tokens.negative)),
      },
      categorical: Object.fromEntries(cats.map((v, i) => [`slot-${i + 1}`, token(v)])),
      sequential: Object.fromEntries(seq.map((v, i) => [`step-${i + 1}`, token(v)])),
      diverging: Object.fromEntries(div.map((v, i) => [`step-${i + 1}`, token(v)])),
    },
  };
  const payload = {
    $metadata: {
      tokenSetOrder: [safeName(exp.name)],
      generator: `chart-palette v${PALETTE_VERSION}`,
    },
    [safeName(exp.name)]: set,
  };
  return JSON.stringify(payload, null, 2) + "\n";
}

/** Single-page SVG swatch sheet — drop into slides or design specs. */
export function toSvg(exp: PaletteExport): string {
  const t = exp.themeA;
  const steps = exp.rampSteps ?? 9;
  const cats = categoricalSlots(t);
  const seq = sequentialStops(t, steps);
  const div = divergingStops(t, steps);
  const bg = hex(t.tokens.bg);
  const fg = hex(t.tokens.axis);
  const surface = hex(t.tokens.surface);

  const W = 880;
  const swatch = 72;
  const gap = 8;
  const labelH = 18;
  const sectionGap = 28;

  function row(y: number, title: string, colors: string[]) {
    const items = colors
      .map((c, i) => {
        const x = i * (swatch + gap);
        return `
          <g transform="translate(${x}, ${y + labelH})">
            <rect width="${swatch}" height="${swatch}" rx="6" fill="${c}" />
            <text x="${swatch / 2}" y="${swatch + 14}" font-size="10" font-family="monospace"
              fill="${fg}" text-anchor="middle">${c}</text>
            <text x="${swatch / 2}" y="${swatch + 26}" font-size="9" font-family="sans-serif"
              fill="${fg}" opacity="0.6" text-anchor="middle">${i + 1}</text>
          </g>`;
      })
      .join("");
    return `
      <g transform="translate(0, ${y})">
        <text x="0" y="12" font-size="11" font-family="sans-serif" font-weight="600"
          fill="${fg}" letter-spacing="1">${title.toUpperCase()}</text>
        ${items}
      </g>`;
  }

  const r1Y = 56;
  const r2Y = r1Y + labelH + swatch + 30 + sectionGap;
  const r3Y = r2Y + labelH + swatch + 30 + sectionGap;
  const H = r3Y + labelH + swatch + 40 + 40;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${bg}" />
  <g transform="translate(24, 24)">
    <rect x="-12" y="-12" width="${W - 24}" height="${H - 24}" rx="10" fill="${surface}" />
    <text x="0" y="14" font-size="14" font-family="sans-serif" font-weight="700" fill="${fg}">
      ${xmlEscape(exp.name)}
    </text>
    <text x="0" y="30" font-size="10" font-family="monospace" fill="${fg}" opacity="0.6">
      palette v${PALETTE_VERSION} · ${t.theme} · posture=${t.posture} · N=${t.effectiveN}
    </text>
    ${row(r1Y, `Categorical (N=${cats.length})`, cats)}
    ${row(r2Y, `Sequential (${seq.length} stops)`, seq)}
    ${row(r3Y, `Diverging (${div.length} stops)`, div)}
  </g>
</svg>
`;
}

export type ExportFormat = "css" | "tailwind" | "echarts" | "figma" | "svg";

export interface FormatDescriptor {
  id: ExportFormat;
  label: string;
  language: string;
  filename: (name: string) => string;
  mime: string;
  build: (exp: PaletteExport) => string;
}

export const EXPORT_FORMATS: FormatDescriptor[] = [
  {
    id: "css",
    label: "CSS variables",
    language: "css",
    filename: (n) => `${safeName(n)}.css`,
    mime: "text/css",
    build: toCss,
  },
  {
    id: "tailwind",
    label: "Tailwind config",
    language: "js",
    filename: (n) => `${safeName(n)}.tailwind.js`,
    mime: "text/javascript",
    build: toTailwind,
  },
  {
    id: "echarts",
    label: "ECharts theme",
    language: "json",
    filename: (n) => `${safeName(n)}.echarts.json`,
    mime: "application/json",
    build: toEChartsTheme,
  },
  {
    id: "figma",
    label: "Figma Tokens",
    language: "json",
    filename: (n) => `${safeName(n)}.tokens.json`,
    mime: "application/json",
    build: toFigmaTokens,
  },
  {
    id: "svg",
    label: "SVG swatches",
    language: "xml",
    filename: (n) => `${safeName(n)}.swatches.svg`,
    mime: "image/svg+xml",
    build: toSvg,
  },
];
