/**
 * Writes the files that exist only for machines: sitemap.xml, robots.txt,
 * llms.txt, llms-full.txt, and a .md twin of every post.
 *
 * Called by scripts/prerender.mjs, which already has the route list and the
 * site metadata loaded out of the SSR bundle - there is one source of truth
 * for what this site contains (src/seo/site.ts) and both the HTML and these
 * files are derived from it.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";

const AI_CRAWLERS = [
  // Answer engines that cite. Each is named rather than left to the wildcard
  // so the intent is explicit and a future disallow is a one-line edit.
  ["GPTBot", "OpenAI - training and ChatGPT browsing"],
  ["OAI-SearchBot", "OpenAI - ChatGPT search index"],
  ["ChatGPT-User", "OpenAI - user-initiated fetch"],
  ["ClaudeBot", "Anthropic - crawler"],
  ["Claude-User", "Anthropic - user-initiated fetch"],
  ["Claude-SearchBot", "Anthropic - search index"],
  ["PerplexityBot", "Perplexity - index"],
  ["Perplexity-User", "Perplexity - user-initiated fetch"],
  ["Google-Extended", "Google - Gemini grounding"],
  ["Applebot-Extended", "Apple Intelligence"],
  ["Amazonbot", "Amazon"],
  ["Bytespider", "ByteDance"],
  ["CCBot", "Common Crawl"],
  ["cohere-ai", "Cohere"],
  ["Meta-ExternalAgent", "Meta"],
  ["DuckAssistBot", "DuckDuckGo"],
];

const CLASSIC_CRAWLERS = ["Googlebot", "Bingbot", "DuckDuckBot", "Twitterbot", "facebookexternalhit", "LinkedInBot", "Slackbot"];

function write(outDir, rel, body) {
  const file = resolve(outDir, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, body);
  return rel;
}

// Files keep their exact path; pages take the trailing slash GitHub Pages
// redirects to, so nothing generated here costs a fetcher a redirect hop.
const fileUrl = (SITE, p) => `${SITE.origin}${SITE.base}${p}`;
const pageUrl = (SITE, p) => (p ? `${SITE.origin}${SITE.base}${p}/` : `${SITE.origin}${SITE.base}`);

function robots(SITE) {
  const lines = [
    "# Every crawler is welcome, including the ones that answer questions",
    "# instead of returning links. Generated by scripts/discovery.mjs.",
    "",
  ];
  for (const name of CLASSIC_CRAWLERS) lines.push(`User-agent: ${name}`, "Allow: /", "");
  lines.push("# Answer engines", "");
  for (const [name, why] of AI_CRAWLERS) lines.push(`# ${why}`, `User-agent: ${name}`, "Allow: /", "");
  lines.push("User-agent: *", "Allow: /", "");
  lines.push(`Sitemap: ${SITE.origin}${SITE.base}sitemap.xml`, "");
  return lines.join("\n");
}

function sitemap(SITE, routeList, staticList) {
  const entries = [
    ...routeList.filter((r) => r.indexable),
    // Static pages carry their own filename, so they are files, not directories.
    ...staticList.map((p) => ({ ...p, indexable: true, isFile: true })),
  ]
    .map((r) => {
      const loc = r.isFile ? fileUrl(SITE, r.path) : pageUrl(SITE, r.path);
      const lastmod = r.lastmod ? `\n    <lastmod>${r.lastmod}</lastmod>` : "";
      return `  <url>\n    <loc>${loc}</loc>${lastmod}\n    <priority>${r.priority.toFixed(1)}</priority>\n  </url>`;
    });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries.join("\n"),
    "</urlset>",
    "",
  ].join("\n");
}

/**
 * llms.txt: the index. A model that fetches one file should learn what is
 * here, what each page answers, and where the full text lives.
 */
function llmsIndex(SITE, routeList, posts) {
  const u = (p) => fileUrl(SITE, p);
  const page = (p) => pageUrl(SITE, p);
  const postLines = posts.map(
    (p) => `- [${p.title}](${u(`blog/${p.slug}.md`)}) ([page](${page(`blog/${p.slug}`)})): ${p.summary}`,
  );
  return `# ${SITE.name}

> ${SITE.description}

Built by ${SITE.author.name} (${SITE.author.url}). Engine version ${SITE.version}.
Every figure published on this site is computed by the engine at render time
against published palette specs, not transcribed by hand.

The measurement stack, stated once: color distance is OKLab ΔE; contrast is
WCAG 2.2 SC 1.4.11 non-text contrast against the chart background, floor 3:1;
colorblind simulation uses the published Machado (2009) matrices for
deuteranopia, protanopia and tritanopia, plus achromatopsia. The honest cap for
a categorical palette is 6 slots - above that no palette keeps its colors
reliably distinct under dichromacy, and this one relaxes its floors and says so.

## Notes

${postLines.join("\n")}

## Tools

- [Interactive builder](${page("")}): solve a categorical palette around fixed brand anchors, audit it against a chosen background, simulate colorblind vision, build sequential and diverging ramps.
- [MCP server](${SITE.mcpDocs}): the same engine as a read-only tool an assistant can call at ${SITE.mcpEndpoint}. Tools: solve_palette, audit_palette, simulate_palette, build_ramp.
- [chart-color-system on npm](${SITE.npm}): the engine as a library. MIT.

## Source

- [Repository](${SITE.repo})
- [Full text of this site as one file](${u("llms-full.txt")})
`;
}

/** llms-full.txt: the index plus the complete text of every note. */
function llmsFull(SITE, routeList, posts, root) {
  const parts = [llmsIndex(SITE, routeList, posts).trimEnd(), ""];
  parts.push("---", "", "# Full text", "");
  for (const post of posts) {
    const src = resolve(root, `docs/posts/${post.slug}.md`);
    if (!existsSync(src)) continue;
    parts.push(`<!-- ${pageUrl(SITE, `blog/${post.slug}`)} · published ${post.date} -->`, "");
    parts.push(readFileSync(src, "utf8").trim(), "");
    parts.push("---", "");
  }
  return parts.join("\n");
}

export function writeDiscovery({ outDir, root, SITE, routeList, staticList, posts }) {
  const written = [];
  written.push(write(outDir, "robots.txt", robots(SITE)));
  written.push(write(outDir, "sitemap.xml", sitemap(SITE, routeList, staticList)));
  written.push(write(outDir, "llms.txt", llmsIndex(SITE, routeList, posts)));
  written.push(write(outDir, "llms-full.txt", llmsFull(SITE, routeList, posts, root)));

  // A .md twin next to each post: the same argument without the markup, for
  // a fetcher that would rather not parse a page to read a paragraph.
  for (const route of routeList) {
    if (!route.markdownSource) continue;
    const src = resolve(root, route.markdownSource);
    if (!existsSync(src)) {
      throw new Error(`markdownSource missing for ${route.path}: ${route.markdownSource}`);
    }
    written.push(write(outDir, `${route.path}.md`, readFileSync(src, "utf8")));
  }
  return written;
}
