/**
 * One mark, everywhere.
 *
 * Before this there were three: a three-bar tile in the sticky bar built from
 * the anchor tokens, a different three-bar tile in favicon.svg, and the ring
 * in figma/brand. Nothing connected them, so each drifted on its own.
 *
 * Every raster and the vector are now generated by figma/scripts/render-brand.py,
 * which audits its own output. These guards cover what that script cannot see:
 * that the app and the documents actually point at what it produces, and that
 * nobody hand-draws a second mark beside it.
 */
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..", "..", "..");
const read = (p: string) => readFileSync(join(ROOT, p), "utf8");

/** The four views the mark is made of, from render-brand.py's VIEWS. */
const VIEWS = ["#f20ddf", "#7092da", "#0075e4", "#888888"];

describe("the brand mark", () => {
  it("ships every surface the markup asks for", () => {
    for (const f of [
      "public/favicon.svg",
      "public/favicon.ico",
      "public/apple-touch-icon.png",
      "public/plugin-icon.png",
      "public/brand/mark-192.png",
      "public/brand/mark-512.png",
      "figma/brand/icon-128.png",
      "figma/brand/icon-512.png",
    ]) {
      expect(existsSync(join(ROOT, f)), f).toBe(true);
    }
  });

  it("is one colour as four people receive it, not a decorative shape", () => {
    const svg = read("public/favicon.svg");
    expect(svg.match(/<path/g)).toHaveLength(4);
    // Each quadrant's gradient starts at that view's own colour.
    for (const hex of VIEWS) {
      expect(svg.toLowerCase(), hex).toContain(hex);
    }
  });

  it("is what the tab, the home screen and the docs page point at", () => {
    const index = read("index.html");
    expect(index).toContain('href="/favicon.svg"');
    expect(index).toContain('href="/favicon.ico"');
    expect(index).toContain('rel="apple-touch-icon"');

    // Served from a project subpath, so its hrefs must stay relative.
    const docs = read("public/mcp-docs.html");
    expect(docs).toContain('href="favicon.svg"');
    expect(docs).not.toContain('href="/favicon.svg"');
  });

  it("is what the app draws in its own chrome", () => {
    const page = read("src/pages/ChartsDemo.tsx");
    expect(page).toContain("favicon.svg");
    // The hand-built three-bar tile that used to sit in the sticky bar.
    expect(page).not.toContain('background: "hsl(var(--chart-cat-anchor-1))"');
  });

  it("is what the plugin promo draws", () => {
    expect(read("src/components/charts/PluginPromo.tsx")).toContain("plugin-icon.png");
  });
});
