/**
 * One mark, everywhere.
 *
 * Before this there were three: a three-bar tile in the sticky bar built from
 * the anchor tokens, a different three-bar tile in favicon.svg, and the ring
 * in figma/brand. Nothing connected them, so each drifted on its own.
 *
 * Every raster and the vector are now generated by figma/scripts/render-brand.py,
 * which audits its own output. These guards cover what that script cannot see:
 * that the app and the documents actually point at what it produces, and that
 * nobody hand-draws a second mark beside it.
 */
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..", "..", "..");
const read = (p: string) => readFileSync(join(ROOT, p), "utf8");

describe("the brand mark", () => {
  it("ships every surface the markup asks for", () => {
    for (const f of [
      "public/brand/mark-32.png",
      "public/brand/mark-96.png",
      "public/favicon.ico",
      "public/apple-touch-icon.png",
      "public/plugin-icon.png",
      "public/brand/mark-192.png",
      "public/brand/mark-512.png",
      "figma/brand/icon-128.png",
      "figma/brand/icon-512.png",
    ]) {
      expect(existsSync(join(ROOT, f)), f).toBe(true);
    }
  });

  it("is the rendered artwork everywhere, never a redrawn variant", () => {
    // There is deliberately no favicon.svg. A hand-authored vector is a second
    // drawing of the mark however close it gets, and a simplified small-size
    // variant is a second mark outright. Every surface is the same render at a
    // different size.
    expect(existsSync(join(ROOT, "public/favicon.svg"))).toBe(false);
    const py = read("figma/scripts/render-brand.py");
    expect(py).not.toContain("SMALL");
    expect(py).not.toContain("svg_mark");
  });

  it("is what the tab, the home screen and the docs page point at", () => {
    const index = read("index.html");
    expect(index).toContain('href="/favicon.ico"');
    expect(index).toContain('href="/brand/mark-192.png"');
    expect(index).toContain('rel="apple-touch-icon"');

    // Served from a project subpath, so its hrefs must stay relative.
    const docs = read("public/mcp-docs.html");
    expect(docs).toContain('href="favicon.ico"');
    expect(docs).not.toContain('href="/favicon.ico"');
  });

  it("is what the app draws in its own chrome", () => {
    const page = read("src/pages/ChartsDemo.tsx");
    expect(page).toContain("brand/mark-96.png");
    // The hand-built three-bar tile that used to sit in the sticky bar.
    expect(page).not.toContain('background: "hsl(var(--chart-cat-anchor-1))"');
  });

  it("is what the plugin promo draws", () => {
    expect(read("src/components/charts/PluginPromo.tsx")).toContain("plugin-icon.png");
  });
});
