/**
 * The solver's output, frozen.
 *
 * Every posture x every N x two backgrounds, with the verdict, the relaxations
 * and the palette. Its real job is to make drift loud: the solver used to
 * return a different answer per JavaScript engine
 * (docs/spikes/engine-divergence.md), and the arithmetic that fixed it is
 * subtle enough that someone could undo it without noticing - a stray
 * Math.pow, an unquantised record - and nothing else in the suite would fail.
 *
 * This file is generated by `node scripts/freeze-palette-sweep.mjs`, and it
 * should only ever be regenerated as part of a deliberate PALETTE_VERSION
 * bump. If it fails at any other time, the solver moved when it should not
 * have.
 *
 * It cannot prove cross-engine agreement on its own - vitest runs one engine.
 * What it proves is that THIS engine still produces the values that all three
 * of Node 24, Chrome 152 and JavaScriptCore were verified to agree on.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { seedTokens } from "@/test/seedTokens";
seedTokens();
import { solveCategorical, auditPalette, fromCss, POSTURE } from "@/charts/index";
import { PALETTE_VERSION } from "@/charts/version";

const GOLDEN = join(__dirname, "__golden__", "palette-sweep.csv");

function sweep(): string {
  const out: string[] = [];
  for (const posture of Object.keys(POSTURE) as Array<keyof typeof POSTURE>) {
    for (let n = 1; n <= POSTURE[posture].maxCategorical; n++) {
      for (const bgHex of ["#ffffff", "#0b0e14"]) {
        const bg = fromCss(bgHex);
        const r = solveCategorical({
          n, posture: posture as never, background: bg, grid: fromCss("#e5e7eb"), locks: [],
        });
        const a = auditPalette(r.palette, bg);
        out.push(
          [posture, n, bgHex, a.overall, r.relaxations.join("+") || "-",
            r.palette.map((c) => c.hex).join("")].join(",")
        );
      }
    }
  }
  return out.join("\n") + "\n";
}

describe("frozen solver output", () => {
  it("still matches the values three engines were verified to agree on", () => {
    const golden = readFileSync(GOLDEN, "utf8");
    const actual = sweep();
    if (actual !== golden) {
      const a = actual.split("\n");
      const g = golden.split("\n");
      const first = a.findIndex((l, i) => l !== g[i]);
      throw new Error(
        `Solver output moved at line ${first + 1}.\n` +
          `  golden: ${g[first]}\n  actual: ${a[first]}\n` +
          `If this is a deliberate change, bump PALETTE_VERSION (currently ${PALETTE_VERSION}) ` +
          `and run: node scripts/freeze-palette-sweep.mjs`
      );
    }
    expect(actual).toBe(golden);
  });

  it("covers every configuration the builder can reach", () => {
    const lines = readFileSync(GOLDEN, "utf8").trim().split("\n");
    const expected = Object.values(POSTURE).reduce((s, p) => s + p.maxCategorical * 2, 0);
    expect(lines).toHaveLength(expected);
  });
});
